## route for register a user
GET http://localhost:5000/api/is-authenticated
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiOTBkMjQ3ZTQtMDQ0NC00NzBhLWFkZDUtNjgyNjNhYmI3YzgyIn0sImlhdCI6MTYzNTM3MzY3OSwiZXhwIjoxNjM1Mzc3Mjc5fQ.qZ-qvewvsKkxBxPbw1rWZswQO2S0aELyp1NHjkYVH2A"
}

## example answers

## sucess:
##
##  json: "true"
##

## error:
##
##  status: 403
##  json: "Not authorize"
##